[package]
name = "csaf-walker"
description = "A library to work with CSAF data"
version = "0.0.2"
edition = "2021"
authors = ["Jens Reimann <ctron@dentrassi.de>"]
license = "Apache-2.0"
repository = "https://github.com/ctron/csaf-walker"
categories = ["data-structures"]
keywords = ["csaf"]
readme = "README.md"
rust-version = "1.63"

[dependencies]
anyhow = "1"
async-trait = "0.1"
bytes = "1"
digest = "0.10.6"
log = "0.4.17"
reqwest = { version = "0.11", features = ["json"] }
sequoia-openpgp = { version = "1" }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10.6"
thiserror = "1"
time = "0.3.20"
tokio = { version = "1", features = ["macros"] }
url = { version = "2.3.1", features = ["serde"] }

[workspace]
members = [
    "csaf-cli"
]