[workspace]
resolver = "2"
members = [
    "csaf",
    "csaf/csaf-cli"
]

[patch.crates-io]
# csaf = { path = "../csaf-rs" }
#csaf = { git = "https://github.com/ctron/csaf-rs", rev = "0bbc262c76c50f7ec918e65d1cf9bf4c5dd564d7" }
