[package]
name = "walker-common"
description = "A common functionality for SBOM and CSAF walker"
version = "0.4.0"
edition = "2021"
authors = ["Jens Reimann <ctron@dentrassi.de>"]
license = "Apache-2.0"
repository = "https://github.com/ctron/csaf-walker"
categories = ["data-structures"]
keywords = ["csaf"]
readme = "README.md"
# based on clap
rust-version = "1.70"

[dependencies]
anyhow = "1"
async-trait = "0.1"
bytes = "1"
clap = { version = "4.3", features = ["derive"] }
csv = "1"
digest = "0.10.7"
flexible-time = "0.1"
humantime = "2"
indicatif = "0.17.6"
log = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
time = { version = "0.3", features = ["serde"] }
url = "2"

sequoia-openpgp = { version = "1", default-features = false }
