name: CI

on:
  push:
    # Run on the main branch
    branches:
      - main
  # Also on PRs, just be careful not to publish anything
  pull_request:
  # Allow to be called from other workflows (like "release")
  workflow_call:
  # But don't trigger on tags, as they are covered by the "release.yaml" workflow

jobs:

  fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Check formatting
        run: |
          cargo fmt --check

  check:

    strategy:
      matrix:

        rust:
          - stable
          - "1.70.0" # MSRV

        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        include:
          - os: ubuntu-latest
            install: sudo apt install clang llvm pkg-config nettle-dev
          - os: windows-latest
            # args: --features crypto-cng --no-default-features
            args: --features vendored,crypto-openssl,walker-common/bzip2-rs --no-default-features

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            frontend/target/
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Rust ${{ matrix.rust }}
        run: |
          rustup install ${{ matrix.rust }}

      - name: Install dependencies
        run: ${{ matrix.install }}

      - name: Check
        run: cargo +${{ matrix.rust }} check --all ${{ matrix.args }}

      - name: Test
        run: cargo +${{ matrix.rust }} test --all ${{ matrix.args }} -- --nocapture

      - name: Install binstall
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo-all-features
        run: |
          cargo binstall -y cargo-all-features

      - name: Check (all features)
        run: |
          cargo check-all-features
